//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MsgDefine.proto
namespace Msg
{
    [global::ProtoBuf.ProtoContract(Name=@"EGameMsgID")]
    public enum EGameMsgID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_UNKNOW", Value=0)]
      EGMI_UNKNOW = 0
    }
  
}