//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MsgShare.proto
// Note: requires additional types generated from: MsgDefine.proto
// Note: requires additional types generated from: MsgBase.proto
namespace Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqEnterGameServer")]
  public partial class ReqEnterGameServer : global::ProtoBuf.IExtensible
  {
    public ReqEnterGameServer() {}
    
    private Msg.Ident _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Msg.Ident id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] account
    {
      get { return _account; }
      set { _account = value; }
    }
    private int _game_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAckEnterGameSuccess")]
  public partial class ReqAckEnterGameSuccess : global::ProtoBuf.IExtensible
  {
    public ReqAckEnterGameSuccess() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}